name: Sync to Upstream

on:
  schedule:
    - cron:  '12 7 * * 1,4'
    # scheduled at 07:12 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
        upstream_repository: amirmasoud/sample-template
        upstream_branch: main
        target_branch: upcoming
#         git_pull_args: '--ff --no-edit'
#         git_pull_args: '--allow-unrelated-histories'
        github_token: ${{ secrets.GITHUB_TOKEN }}
